
<?php  $this->asDialog = true; ?> 

<?php  $dataProvider = new CArrayDataProvider($rawData=$model->Routings, array()); ?> 

<?php 	
		/*$criteria=new CDbCriteria;
		$criteria->condition = "id_cliente=".$model->id_cliente;								
		$dataProvider = new CActiveDataProvider('Direcciones', array(
			'criteria'=>$criteria,
			'sort'=>array(
			    'defaultOrder'=>'id_direccion ASC',
			),			
		));*/
?> 

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'routings-grid',
	'dataProvider'=>$dataProvider,
	'type' => 'hover striped bordered condensed',
	'selectableRows'=>1,	
	'template' => "{summary}\n{pager}\n{items}\n{summary}\n{pager}",	
	'htmlOptions'=>array('style'=>'cursor: pointer;'),
	'pager'=>array(
		'class' => 'bootstrap.widgets.TbPager',
		'displayFirstAndLast' => true,
		//'class' 		 => 'CLinkPager', 
        'header'         => '',
        'firstPageLabel' => TbHtml::icon(TbHtml::ICON_FAST_BACKWARD),
        'prevPageLabel'  => TbHtml::icon(TbHtml::ICON_STEP_BACKWARD),
        'nextPageLabel'  => TbHtml::icon(TbHtml::ICON_STEP_FORWARD),
        'lastPageLabel'  => TbHtml::icon(TbHtml::ICON_FAST_FORWARD),
    ), 		
	'columns'=>array(
		'id_routing',
		'cotizacion_id',
		//array('name'=>'vendedor_id','value'=> 'isset($data->vendedor) ? $data->vendedor->pw_name : $data->vendedor_id '),
		'order_no',
		'reference',
		'fecha',
		/*
		//array('name'=>'id_routing_type','value'=> 'isset($data->idRoutingType) ? $data->idRoutingType->descripcion : $data->id_routing_type '),
		//array('name'=>'id_cliente','value'=> 'isset($data->idCliente) ? $data->idCliente->codigo_tributario : $data->id_cliente '),
		//array('name'=>'id_shipper','value'=> 'isset($data->idShipper) ? $data->idShipper->codigo_tributario : $data->id_shipper '),
		//array('name'=>'id_notify','value'=> 'isset($data->idNotify) ? $data->idNotify->codigo_tributario : $data->id_notify '),
		'no_piezas_old',
		'peso_old',
		'volumen_old',
		'ciudad_origen',
		'ciudad_destino',
		'no_embarque',
		//array('name'=>'id_incoterms','value'=> 'isset($data->idIncoterms) ? $data->idIncoterms->descripcion : $data->id_incoterms '),
		'bodega_prov_emb',
		//array('name'=>'id_transporte','value'=> 'isset($data->idTransporte) ? $data->idTransporte->descripcion : $data->id_transporte '),
		'tramite_aduanal',
		'seguro',
		'porcentaje_seguro',
		'lugar_entrega',
		'solicitado_por',
		'observaciones',
		'mbl_id_shipper',
		'mbl_id_cliente',
		'mbl_id_notify',
		'mbl_net_rate',
		'mbl_selling_rate',
		'mbl_rate_comment',
		'activo',
		'last_user_edit',
		'last_date_edit',
		'delete_user',
		'delete_date',
		//array('name'=>'agente_id','value'=> 'isset($data->agente0) ? $data->agente0->direccion : $data->agente_id '),
		'routing_no',
		'routing',
		//array('name'=>'id_pais','value'=> 'isset($data->idPais) ? $data->idPais->descripcion : $data->id_pais '),
		'import_export',
		'factura_id',
		//array('name'=>'comodity_id','value'=> 'isset($data->comodity) ? $data->comodity->nameen : $data->comodity_id '),
		//array('name'=>'id_container_type','value'=> 'isset($data->idContainerType) ? $data->idContainerType->short_name : $data->id_container_type '),
		//array('name'=>'id_naviera','value'=> 'isset($data->idNaviera) ? $data->idNaviera->nit : $data->id_naviera '),
		//array('name'=>'id_unidad_peso','value'=> 'isset($data->idUnidadPeso) ? $data->idUnidadPeso->descripcion_unidad : $data->id_unidad_peso '),
		//array('name'=>'id_unidad_volumen','value'=> 'isset($data->idUnidadVolumen) ? $data->idUnidadVolumen->descripcion_unidad : $data->id_unidad_volumen '),
		//array('name'=>'id_unidad_peso_vol','value'=> 'isset($data->idUnidadPesoVol) ? $data->idUnidadPesoVol->descripcion_unidad : $data->id_unidad_peso_vol '),
		'peso_volumentrico',
		//array('name'=>'id_truck_type','value'=> 'isset($data->idTruckType) ? $data->idTruckType->short_name : $data->id_truck_type '),
		//array('name'=>'id_tipo_paquete','value'=> 'isset($data->idTipoPaquete) ? $data->idTipoPaquete-> : $data->id_tipo_paquete '),
		//array('name'=>'id_pais_origen','value'=> 'isset($data->idPaisOrigen) ? $data->idPaisOrigen->descripcion : $data->id_pais_origen '),
		//array('name'=>'id_pais_destino','value'=> 'isset($data->idPaisDestino) ? $data->idPaisDestino->descripcion : $data->id_pais_destino '),
		'id_puerto_embarque',
		'id_puerto_desembarque',
		//array('name'=>'carrier_id','value'=> 'isset($data->carrier) ? $data->carrier->name : $data->carrier_id '),
		//array('name'=>'id_facturar','value'=> 'isset($data->idFacturar) ? $data->idFacturar->codigo_tributario : $data->id_facturar '),
		'airportid_embarque',
		'prepaid',
		'airportid_desembarque',
		'borrado',
		'id_sales_support',
		'id_usuario_creacion',
		'hora_ingreso',
		'notificar_a',
		'pais_origen_carga',
		'codigo_exportador',
		//array('name'=>'tarifa_aplicada','value'=> 'isset($data->tarifaAplicada) ? $data->tarifaAplicada->descripcion : $data->tarifa_aplicada '),
		'routing_secc',
		'routing_cli',
		'routing_int',
		'routing_eci',
		'routing_ag',
		'voyage_id',
		'source',
		'wms_bl_id',
		'ancho',
		'alto',
		'largo',
		'tmp_piezas',
		'tmp_peso',
		'tmp_volumen',
		'piezas_entregadas_wms',
		'tipo_documento',
		'id_solicitud',
		'id_shipper_cliente',
		'id_tarifario_costo',
		'id_coloader',
		'no_piezas',
		'peso',
		'volumen',
		'id_colectar',
		'idbitalpemusa',
		'numbitalpemusa',
		'valor_flete_manifestar',
		'poliza_seguro',
		'container_qty',
		'routing_seg',
		'referencia',
		'routing_fac',
		'bl_id',
		'no_bl',
		'id_cliente_order',
		'routing_adu',
		'routing_ter',
		'routing_copy',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',			
			'template'=>'{update}', //{delete}',
			'header' => CHtml::link('<span class="icon-plus icon-white"></span>',Yii::app()->controller->createUrl('/Routings/create'),array('class'=>'btn btn-small btn-primary','onclick'=>'if ("' . $this->asDialog . '") { crud_frame_adjust($(this).attr("href"),"'.Yii::t('app','Create').' '.Yii::t('app','Routings').'",1); return false; }', 'style' => 'display:' . (Yii::app()->session['permisos']['routings']['routings']['create'] == 1 ? 'inline' : 'none'))),			
            'buttons'=>array(            	
                'update'=>
                    array(                    	
                	 	'url'=>'$this->grid->controller->createUrl("/Routings/update", array("id"=>$data->primaryKey))',
						'options'=>array(
    						'onclick'=>'if ("' . $this->asDialog . '") { crud_frame_adjust($(this).attr("href"),"'.Yii::t('app','Update').' '.Yii::t('app','Routings').'",2); return false; }',
	                    ),
	                    'visible' => Yii::app()->session['permisos']['routings']['routings']['update'] == 1 ? 'true' : 'false',
                   	),
                'delete'=>
                    array(                    	
                	 	'url'=>'$this->grid->controller->createUrl("/Routings/delete", array("id"=>$data->primaryKey))',),                   	
            ),				
		),
	),
)); ?>


<?php  $this->asDialog = false; ?> 